### ISSUE TITLE
Changelog is not posted

### ISSUE THREAD

**Issue by Weakky** [prisma-labs/dripip#80]
## Description

Second time that I use dripip to release a stable and that the changelog is not posted. Here's the error:

```
Error: Failed to publish changelog
RequestError [HttpError]: Not Found
    at ~/projects/prisma/nexus-plugin-prisma/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HttpError',
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 11 May 2020 16:33:00 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '2904:41157:65AF117:759CD4B:5EB97E3C',
    'x-ratelimit-limit': '60',
    'x-ratelimit-remaining': '58',
    'x-ratelimit-reset': '1589218380',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/graphql-nexus/plugin-prisma/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/17.0.0 octokit-core.js/2.4.2 Node.js/12.13.1 (macOS Catalina; x64)',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"prerelease":false,"tag_name":"0.8.0","draft":false,"body":"#### BREAKING CHANGES//n//n- 37c3bd9 support prisma 2 beta 4 (#111)//n- b8677cd support prisma 2 beta 3 (#109)//n- c0d702e allow passing a
```

**Comment by williamluke4** [comment]
Having the exact same issue

**Comment by williamluke4** [comment]
https://github.com/prisma-labs/dripip/issues/71
